### ISSUE TITLE
How to change the camera model from "SIMPLE_RADIAL" to "PINHOLE"?

### ISSUE THREAD

**Issue by anterrrr** [colmap/pycolmap#145] opened 2023-06-06 17:54 UTC
![image](https://github.com/colmap/pycolmap/assets/130300209/11b15e0c-a697-473f-8bfe-02b6cfd39dc9)

**Comment by Skydes** [comment] 2023-06-06 21:28
Duplicate of https://github.com/cvg/Hierarchical-Localization/issues/278.

**Closed by Skydes** 2023-06-06 21:28 UTC
